# Generated by Django 5.2 on 2025-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_item',
            new_name='order',
        ),
    ]
