# Generated by Django 5.2 on 2025-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('description', models.TextField(max_length=500, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='imagen')),
            ],
        ),
    ]
